name: build libbarrett

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  build_libbarrett:
    runs-on: ${{ inputs.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: apt update and upgrade
      run: |
        sudo apt update
        sudo apt upgrade -y

    - name: Install dependencies
      run: |
        sudo apt install libgsl-dev libconfig++-dev graphviz doxygen

    - name: Patch libconfig
      run: |
        cd /usr/include
        sudo patch < ${{github.workspace}}/libconfig.patch

    - name: Build
      run: |
        mkdir build
	cd ./build
	cmake ..
	make

    - name: Build documents of libbarrett
      run: |
        doxygen

    - name: Upload artifact of libbarrett
      uses: actions/upload-pages-artifact@v4
      with:
        path: ./docs/html

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v5

