name: build libbarrett

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  build_libbarrett:
    runs-on: ${{ inputs.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: apt update and upgrade
      run: |
        sudo apt update
        sudo apt upgrade -y
	with:
	  ref: ${{ inputs.branch }}

    - name: Install dependencies
      run: |
        sudo apt install libboost-all-dev libeigen3-dev libncurses-dev libgsl-dev libconfig++-dev graphviz doxygen

    - name: Patch libconfig
      run: |
        cd /usr/include
        sudo patch < ${{github.workspace}}/libconfig.patch

    - name: Build
      run: |
        mkdir build
        cd ./build
        cmake ..
        make
        sudo make install

    - name: Build documents of libbarrett
      run: |
        doxygen

    - name: Upload artifact of libbarrett
      uses: actions/upload-pages-artifact@v4
      with:
        path: ./doc/html

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v5
