name: noble-build
on: push

jobs:
  noble-build:
    uses: ./.github/workflows/build.yaml
    with:
      os: ubuntu-24.04
      branch: devel-aist

permissions:
  contents: write
  pages: write
  id-token: write
